name: Pre-Deployment Verification

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verify-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run ESLint
        run: npm run lint
        
      - name: TypeScript check
        run: npm run typecheck
        
      - name: Build project
        run: npm run build
        
      - name: Check for common issues
        run: |
          echo "Checking for common deployment issues..."
          
          # Check for 'any' types
          if grep -r "any" --include="*.ts" --include="*.tsx" .; then
            echo "⚠️  Warning: Found 'any' types in TypeScript files"
          fi
          
          # Check for unused variables
          if npm run lint 2>&1 | grep -q "is assigned a value but never used"; then
            echo "⚠️  Warning: Found unused variables"
          fi
          
      - name: Deployment readiness
        run: |
          echo "✅ All checks passed!"
          echo "Ready for Vercel deployment"