name: Chromatic Usage Monitor

on:
  schedule:
    # Täglich um 9 Uhr UTC
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  monitor:
    name: Monitor Snapshot Usage
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check Chromatic Usage
        id: check-usage
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        run: |
          OUTPUT=$(node scripts/chromatic-usage.js)
          echo "$OUTPUT"
          
          # Extract usage percentage
          USAGE=$(echo "$OUTPUT" | grep -oP '(?<=Usage: )\d+')
          echo "usage=$USAGE" >> $GITHUB_OUTPUT
          
          # Check if over 80%
          if [ "$USAGE" -gt 80 ]; then
            echo "high_usage=true" >> $GITHUB_OUTPUT
          else
            echo "high_usage=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Issue if High Usage
        if: steps.check-usage.outputs.high_usage == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const usage = ${{ steps.check-usage.outputs.usage }};
            const title = `⚠️ Chromatic Snapshot Usage at ${usage}%`;
            const body = `## Chromatic Usage Alert
            
            Der monatliche Snapshot-Verbrauch hat ${usage}% erreicht.
            
            ### Empfohlene Maßnahmen:
            - Reduzieren Sie die Anzahl der Visual Tests
            - Verwenden Sie \`@critical\` Tags für wichtige Tests
            - Überprüfen Sie die Chromatic-Konfiguration
            
            ### Aktuelle Limits:
            - Free Tier: 5.000 Snapshots/Monat
            - Aktueller Verbrauch: ~${Math.round(5000 * usage / 100)} Snapshots
            
            [Chromatic Dashboard](https://www.chromatic.com/manage?appId=YOUR_APP_ID)
            `;
            
            // Check if issue already exists
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'chromatic-usage'
            });
            
            if (issues.data.length === 0) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: body,
                labels: ['chromatic-usage', 'monitoring']
              });
            }