name: deploy
on:
  push:
    branches: [main]
  workflow_dispatch: {}

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install (npm workspaces)
        run: npm ci

      - name: Pull (production)
        run: npx vercel pull --yes --environment=production
        env: 
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Build (prebuilt, prod)
        run: npx vercel build --prod
        env: 
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy (prebuilt → prod)
        run: npx vercel deploy --prebuilt --prod
        env: 
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}