name: Deploy to Vercel

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    if: github.repository == 'Bernhard-Reiter/voai-ux-ui'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          
      - name: Install dependencies (no frozen lockfile)
        run: pnpm install --no-frozen-lockfile
        
      - name: Build showcase
        run: pnpm build --filter=showcase
        
      - name: Deploy to Vercel (voai-website)
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: prj_DaI9YWeNQ274iiVYIQgHzpWPLga5
          vercel-args: '--prod'
          working-directory: ./apps/showcase