name: Deploy

# This workflow is deprecated - deployment is now handled by the main CI workflow
# See .github/workflows/ci.yml for the integrated deployment process

on:
  workflow_dispatch:

permissions:
  contents: write
  deployments: write

jobs:
  deploy:
    name: Manual Deploy to Vercel
    runs-on: ubuntu-latest
    environment: production
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      N8N_API_URL: ${{ secrets.N8N_API_URL }}
      N8N_API_KEY: ${{ secrets.N8N_API_KEY }}
      N8N_WEBHOOK_URL: ${{ secrets.N8N_WEBHOOK_URL }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - run: pnpm turbo run build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: ./
