name: Deploy (Prebuilt) to Vercel
on:
  push:
    branches: [main]
  workflow_dispatch: {}

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies (npm workspaces)
        run: npm ci --workspaces --include-workspace-root=false

      - name: Pull Vercel env (Production)
        run: npx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      # Wichtig: am Repo-Root bauen → erzeugt .vercel/output
      - name: Build with Vercel (prebuilt)
        run: npx vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy prebuilt to Production
        run: npx vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}