name: Design System

on:
  push:
    paths:
      - 'external/voai-ui/**'
    branches: [main, develop]
  pull_request:
    paths:
      - 'external/voai-ui/**'
    branches: [main, develop]
  workflow_dispatch:

jobs:
  build-tokens:
    name: Build Design Tokens
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Build tokens
        run: pnpm build:tokens
        
      - name: Verify token build
        run: |
          if [ ! -f "external/voai-ui/packages/tokens/build/tokens.json" ]; then
            echo "Error: tokens.json not found"
            exit 1
          fi
          if [ ! -f "external/voai-ui/packages/tokens/build/variables.css" ]; then
            echo "Error: variables.css not found"
            exit 1
          fi
          echo "Design tokens built successfully!"
        
      - name: Upload token artifacts
        uses: actions/upload-artifact@v4
        with:
          name: design-tokens
          path: |
            external/voai-ui/packages/tokens/build/