name: Fix Lockfile

on:
  pull_request:
    types: [labeled]

jobs:
  fix-lockfile:
    if: contains(github.event.label.name, 'lockfile-fix')
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
          
      - uses: pnpm/action-setup@v3
        with:
          version: 9
          
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          
      - name: Update lockfile
        run: |
          rm -f pnpm-lock.yaml
          pnpm install --no-frozen-lockfile
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pnpm-lock.yaml
          git diff --staged --quiet || git commit -m "fix: update pnpm-lock.yaml"
          git push
