name: Update GitHub Secrets Guide

# This is a template workflow that shows how to update secrets
# GitHub Actions cannot update its own secrets for security reasons
# You must update them manually through the GitHub UI

on:
  workflow_dispatch:

jobs:
  display-instructions:
    runs-on: ubuntu-latest
    steps:
      - name: Display Secret Update Instructions
        run: |
          echo "📋 GitHub Secrets Update Instructions"
          echo "====================================="
          echo ""
          echo "1. Go to: https://github.com/Bernhard-Reiter/voai-website/settings/secrets/actions"
          echo ""
          echo "2. Update the following secrets:"
          echo ""
          echo "   SUPABASE_SERVICE_ROLE_KEY:"
          echo "   eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxdm5hc3VwdXRhdHBodnFycWFtIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0OTU4MDcyNSwiZXhwIjoyMDY1MTU2NzI1fQ.o0EzGNGZ1G1R9pjKWkRAAA4KjJVi5naJMNaOj0AEGTQ"
          echo ""
          echo "   NEXT_PUBLIC_SUPABASE_ANON_KEY:"
          echo "   eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxdm5hc3VwdXRhdHBodnFycWFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1ODA3MjUsImV4cCI6MjA2NTE1NjcyNX0.8uHezlmnL4okIZPH4vSh-MEANyF-_UkILE65hFV_60w"
          echo ""
          echo "3. Click on each secret and update its value"
          echo ""
          echo "4. Save the changes"
          echo ""
          echo "✅ Once updated, your GitHub Actions will use the new keys automatically"
